### ISSUE TITLE
Lack of requirements.txt

### ISSUE THREAD

**Issue by mstechly** [CodieKev/QGames#1]
This repo could use requirements.txt so it's easier to set up :)
Especially that qiskit tents to change rather rapidly and it might break with new release.

**Comment by CodieKev** [comment]
I have created the file with data of the current versions of Qiskit, Python, and Pygames on which the program was made.
I would try to keep it updated with any new drastic version change in any of the three modules used.
Thank You Michal Sir for your time and Feedback.
