### ISSUE TITLE
Requirements.txt has a wrong format

### ISSUE THREAD

**Issue by mstechly** [CodieKev/QGames#4]
In the current format you cannot use it with `pip install -r requirements.txt`.
To see how it should look like, see e.g.: [here](https://medium.com/featurepreneur/install-python-packages-pip-and-requirements-txt-652cd5e335)

**Comment by CodieKev** [comment]
Sorry, I thought requirement.txt is just the list of requirements for the program to run. I would learn how to make the executable file and update it as soon as possible.

**Comment by mstechly** [comment]
No problem, that’s just one way of learning :)
